/* NyXiaLabo — Studio Écriture IA interne. */
(function(){
'use strict';
const WRITERS={
 alex:{name:'Alex',emoji:'✍️',sub:'Maître d’écriture et architecte narratif',greeting:'Quelle histoire, scène ou idée aimerais-tu faire avancer aujourd’hui?',persona:'Tu es Alex, maître d’écriture et architecte narratif. Tu aides à bâtir une structure solide, une progression dramatique claire, des personnages cohérents et des chapitres complets.'},
 aimee:{name:'Aimée',emoji:'🌹',sub:'Romance & relations émotionnelles',greeting:'Quelle relation ou émotion aimerais-tu rendre plus vivante dans ton histoire?',persona:'Tu es Aimée, spécialiste de romance et de relations émotionnelles. Tu écris des liens crédibles, du désir, de la vulnérabilité, des conflits relationnels et des évolutions affectives nuancées.'},
 alibi:{name:'Alibi',emoji:'🔎',sub:'Policier, enquête & thriller',greeting:'Quelle enquête, fausse piste ou révélation aimerais-tu construire?',persona:'Tu es Alibi, spécialiste du policier, de l’enquête et du thriller. Tu maîtrises indices, fausses pistes, révélations, rythme, suspense, logique d’enquête et tension.'},
 abime:{name:'Abîme',emoji:'🖤',sub:'Horreur psychologique & atmosphérique',greeting:'Quelle peur, tension ou atmosphère aimerais-tu faire naître dans ton histoire?',persona:'Tu es Abîme, spécialiste de l’horreur psychologique et atmosphérique. Tu construis une inquiétude progressive, une ambiance sensorielle, une tension mentale et des images fortes sans sacrifier la cohérence.'},
 constance:{name:'Constance',emoji:'🎭',sub:'Drames humains & émotions',greeting:'Quel conflit humain ou parcours émotionnel aimerais-tu approfondir?',persona:'Tu es Constance, spécialiste des drames humains et des émotions. Tu écris des conflits crédibles, des dilemmes, de la profondeur psychologique et des trajectoires émotionnelles fortes.'},
 fripouille:{name:'Fripouille',emoji:'🐾',sub:'Contes jeunesse & imaginaire doux',greeting:'Quelle petite aventure aimerais-tu inventer pour émerveiller les enfants?',persona:'Tu es Fripouille, spécialiste des contes jeunesse et de l’imaginaire doux. Tu adaptes vocabulaire, rythme, enjeux et humour au jeune public tout en racontant une vraie histoire.'},
 melusine:{name:'Mélusine',emoji:'🌙',sub:'Fantasy, imaginaire & science-fiction',greeting:'Quel monde, pouvoir ou mystère aimerais-tu faire naître aujourd’hui?',persona:'Tu es Mélusine, spécialiste de fantasy, d’imaginaire et de science-fiction. Tu construis des mondes cohérents, des systèmes de magie ou technologies crédibles, des cultures, des enjeux et une narration immersive.'},
 nyxia:{name:'NyXia',emoji:'💜',sub:'Direction créative & cohérence transversale',greeting:'Qu’aimerais-tu écrire, développer ou vérifier dans ton livre aujourd’hui?',persona:'Tu es NyXia en mode écriture. Tu agis comme directrice créative transversale : tu relies structure, voix, émotion, cohérence et intention de l’autrice sans uniformiser son style.'}
};
const MODELS={'aion-labs/aion-3.5-mini':'Aion 3.5 Mini','openai/gpt-5.2':'GPT','z-ai/glm-5.2':'Z'};
const params=new URLSearchParams(location.search);let agent=params.get('agent')||'alex';if(!WRITERS[agent])agent='alex';
let token=params.get('t')||'';try{if(!token&&window.parent&&window.parent!==window)token=window.parent.sessionStorage.getItem('sandbox_token')||''}catch(_){};if(!token)try{token=sessionStorage.getItem('sandbox_token')||''}catch(_){}
const $=id=>document.getElementById(id);let busy=false,lastUser='',lastAnswer='';
const keys={knowledge:'nyxia_ecriture_knowledge_v1',settings:'nyxia_ecriture_settings_v1'};
function storeGet(k,fallback){try{const v=localStorage.getItem(k);return v?JSON.parse(v):fallback}catch(_){return fallback}}
function storeSet(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_){status('Stockage local plein : retire quelques connaissances.','bad');return false}}
function safeId(s){return String(s||'livre').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'livre'}
function settings(){return storeGet(keys.settings,{bookTitle:'Mon livre',bookMemory:'',model:'aion-labs/aion-3.5-mini',words:4500})}
function saveSettings(){const s={bookTitle:$('book-title').value.trim()||'Mon livre',bookMemory:$('book-memory').value,model:$('model-select').value,words:Number($('words-select').value)||4500};storeSet(keys.settings,s);return s}
function historyKey(){const s=settings();return 'nyxia_ecriture_chat_'+safeId(s.bookTitle)+'_'+agent}
function history(){return storeGet(historyKey(),[])}
function saveHistory(h){storeSet(historyKey(),h.slice(-60))}
function knowledge(){return storeGet(keys.knowledge,[])}
function saveKnowledge(k){storeSet(keys.knowledge,k.slice(0,80));renderKnowledge()}
function status(msg,kind){const e=$('status');e.textContent=msg||'';e.className='status'+(kind?' '+kind:'')}
function init(){const w=WRITERS[agent],s=settings();$('writer-emoji').textContent=w.emoji;$('writer-name').textContent=w.name;$('writer-sub').textContent=w.sub;$('empty-title').textContent='Écriture avec '+w.name;$('empty-greeting').textContent=w.greeting;$('model-select').value=MODELS[s.model]?s.model:'aion-labs/aion-3.5-mini';$('words-select').value=String(s.words||4500);$('book-title').value=s.bookTitle||'Mon livre';$('book-memory').value=s.bookMemory||'';renderHistory();renderKnowledge();wire();updateCounter()}
function wire(){
 $('send').onclick=send;$('new-chat').onclick=newChat;$('continue').onclick=continueChapter;$('anchor').onclick=anchorChapter;$('mic').onclick=startDictation;$('side-toggle').onclick=()=> $('side').classList.toggle('open');
 $('model-select').onchange=saveSettings;$('words-select').onchange=saveSettings;$('book-title').onchange=()=>{saveSettings();renderHistory()};$('book-memory').onchange=saveSettings;$('book-memory').oninput=debounce(saveSettings,500);
 $('knowledge-add').onclick=addPastedKnowledge;$('knowledge-clear').onclick=clearKnowledge;$('knowledge-file').onchange=importKnowledgeFiles;$('input').oninput=updateCounter;$('input').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();send()}};
}
let debounceTimer;function debounce(fn,ms){return function(){clearTimeout(debounceTimer);debounceTimer=setTimeout(fn,ms)}}
function updateCounter(){$('counter').textContent=$('input').value.length+' caractères'}
function renderHistory(){const box=$('messages'),h=history();box.replaceChildren();if(!h.length){const empty=document.createElement('div');empty.className='empty';empty.id='empty';empty.innerHTML='<h2>'+escapeHtml('Écriture avec '+WRITERS[agent].name)+'</h2><p>'+escapeHtml(WRITERS[agent].greeting)+'</p><span class="pill">Chapitre complet · une seule génération · continuité · connaissances injectées</span>';box.appendChild(empty);lastAnswer='';return}h.forEach(m=>appendMessage(m.role,m.content,false));lastAnswer=[...h].reverse().find(m=>m.role==='assistant')?.content||'';box.scrollTop=box.scrollHeight}
function appendMessage(role,text,save=true){const box=$('messages');box.querySelector('.empty')?.remove();const wrap=document.createElement('div');wrap.className='msg '+(role==='user'?'user':'assistant');const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;wrap.appendChild(bubble);if(role==='assistant'){const acts=document.createElement('div');acts.className='msg-actions';const listen=mini('🔊 Écouter',()=>speak(text));const copy=mini('📋 Copier',()=>navigator.clipboard?.writeText(text));const retry=mini('↺ Réessayer',()=>retryLast());acts.append(listen,copy,retry);bubble.appendChild(acts)}box.appendChild(wrap);box.scrollTop=box.scrollHeight;if(save){const h=history();h.push({role,content:text,at:Date.now()});saveHistory(h)}}
function mini(label,fn){const b=document.createElement('button');b.className='mini';b.type='button';b.textContent=label;b.onclick=fn;return b}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s||'';return d.innerHTML}
function tokenize(s){return Array.from(new Set(String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-z0-9]{4,}/g)||[])).filter(x=>!['dans','avec','pour','mais','plus','tout','cette','comme','etre','avoir','chapitre','livre','texte'].includes(x))}
function chunks(text,size=3600,overlap=300){text=String(text||'').trim();const out=[];for(let i=0;i<text.length;i+=size-overlap){out.push(text.slice(i,i+size));if(out.length>=120)break}return out}
function relevantKnowledge(query){const words=tokenize(query);const scored=[];knowledge().forEach(doc=>chunks(doc.text).forEach((c,i)=>{const low=c.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');let score=0;words.forEach(w=>{if(low.includes(w))score++});if(score||scored.length<4)scored.push({score,text:c,title:doc.title,index:i})}));scored.sort((a,b)=>b.score-a.score);let used=0,res=[];for(const x of scored){if(used+x.text.length>16000)continue;res.push('['+x.title+']\n'+x.text);used+=x.text.length;if(res.length>=5)break}return res.join('\n\n---\n\n')}
function systemPrompt(userText,mode){const s=saveSettings(),w=WRITERS[agent],k=relevantKnowledge(userText+' '+s.bookMemory);return `${w.persona}\n\nTu travailles pour Diane dans son atelier privé d'écriture. Respecte sa direction créative et son texte existant.\n\nRÈGLES DE CADENCE ROMAN :\n- Quand la demande concerne un chapitre, rédige un chapitre LONG, COMPLET et directement utilisable, visant environ ${s.words} mots sauf instruction contraire.\n- Ne remplace jamais un chapitre demandé par un résumé, un plan ou des conseils. Écris le texte du chapitre.\n- Développe scènes, dialogues, actions, transitions, sensations et sous-texte. Évite les répétitions et le remplissage artificiel.\n- Garde une continuité stricte avec la mémoire du livre et les messages précédents.\n- Termine sur une vraie fin de chapitre, sauf si Diane demande explicitement de poursuivre une scène.\n- Le chapitre doit être livré EN UNE SEULE RÉPONSE complète : ne le découpe jamais en Partie 1, Partie 2, suite, segments ou épisodes.\n- Ne propose pas de continuer plus tard et ne termine pas sur un marqueur de type [SUITE POSSIBLE].\n- Gère toi-même la cadence, la densité et le rythme pour faire tenir le chapitre complet dans la réponse tout en visant la longueur demandée.\n- Français naturel, fluide et littéraire. Aucun ton d'assistant générique.\n\nPROJET : ${s.bookTitle}\nMÉMOIRE / CONTINUITÉ DU LIVRE :\n${s.bookMemory||'(aucune mémoire ajoutée pour le moment)'}\n\nCONNAISSANCES D'ÉCRITURE PERTINENTES :\n${k||'(aucune connaissance pertinente injectée)'}\n\nMODE : ${mode||'écriture'}`}
async function callModel(messages,system,maxTokens=24000,temp=.84){const model=$('model-select').value;const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({providerId:'openrouter',model,system_prompt:system,max_tokens:maxTokens,temperature:temp,messages})});const raw=await r.text();let d={};try{d=JSON.parse(raw)}catch(_){throw Error('Réponse serveur illisible ('+r.status+')')}if(!r.ok||d.error)throw Error(d.error||('Erreur '+r.status));return String(d.text||'').trim()}
async function send(){if(busy)return;const text=$('input').value.trim();if(!text)return;lastUser=text;$('input').value='';updateCounter();appendMessage('user',text);busy=true;$('send').disabled=true;status(MODELS[$('model-select').value]+' écrit…');const typing=document.createElement('div');typing.className='msg assistant typing';typing.textContent='✦ rédaction en cours…';$('messages').appendChild(typing);$('messages').scrollTop=$('messages').scrollHeight;try{const h=history().filter(m=>m.role==='user'||m.role==='assistant').slice(-18).map(m=>({role:m.role,content:m.content}));const reply=await callModel(h,systemPrompt(text,'rédaction longue'));typing.remove();lastAnswer=reply;appendMessage('assistant',reply);status('Chapitre / réponse terminé avec '+MODELS[$('model-select').value]+'.','ok')}catch(e){typing.remove();status(e.message,'bad')}finally{busy=false;$('send').disabled=false}}
async function retryLast(){if(busy||!lastUser)return;const h=history();while(h.length&&h[h.length-1].role==='assistant')h.pop();if(h.length&&h[h.length-1].role==='user')h.pop();saveHistory(h);renderHistory();$('input').value=lastUser;send()}
async function continueChapter(){if(!lastAnswer){status('Aucun chapitre à continuer.','bad');return}$('input').value='Continue exactement ce chapitre à partir de la dernière phrase, sans recommencer ni résumer. Développe la suite jusqu’à une vraie fin de chapitre.';updateCounter();send()}
async function anchorChapter(){if(busy||!lastAnswer){status('Aucun chapitre à ancrer dans la mémoire.','bad');return}busy=true;$('anchor').disabled=true;status('Extraction de la continuité du chapitre…');try{const prompt='Transforme ce chapitre en mémoire de continuité concise pour écrire la suite : personnages présents, événements, révélations, changements émotionnels, objets/indices, lieux, promesses narratives, chronologie et éléments à ne pas contredire. Ne réécris pas le chapitre.\n\nCHAPITRE :\n'+lastAnswer.slice(0,50000);const summary=await callModel([{role:'user',content:prompt}],systemPrompt(prompt,'mémoire de continuité'),1800,.2);const area=$('book-memory');area.value=(area.value.trim()?area.value.trim()+'\n\n':'')+'--- Mémoire ajoutée '+new Date().toLocaleDateString('fr-CA')+' ---\n'+summary;saveSettings();status('Mémoire du chapitre ajoutée.','ok')}catch(e){status(e.message,'bad')}finally{busy=false;$('anchor').disabled=false}}
function newChat(){if(!confirm('Commencer une nouvelle conversation avec '+WRITERS[agent].name+' pour ce livre ?'))return;localStorage.removeItem(historyKey());lastAnswer='';lastUser='';renderHistory();status('Nouveau chat prêt.','ok')}
function cleanSpeech(t){return String(t||'').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/\*([^*]+)\*/g,'$1').replace(/#{1,6}\s+/g,'').replace(/`([^`]+)`/g,'$1').replace(/\[[A-Z_]+[^\]]*\]/g,'').trim()}
function pickVoice(){const vs=speechSynthesis.getVoices()||[];return vs.find(v=>/^fr-FR$/i.test(v.lang))||vs.find(v=>/^fr(?!-CA)/i.test(v.lang))||vs.find(v=>/^fr/i.test(v.lang))||null}
function speak(text){if(!('speechSynthesis'in window))return status('TTS du navigateur indisponible.','bad');speechSynthesis.cancel();const clean=cleanSpeech(text);const parts=clean.match(/[\s\S]{1,1800}(?:[.!?]\s|$)/g)||[clean];let i=0;function next(){if(i>=parts.length)return;const u=new SpeechSynthesisUtterance(parts[i++]);u.lang='fr-FR';const v=pickVoice();if(v)u.voice=v;u.rate=.98;u.onend=next;speechSynthesis.speak(u)}next()}
function startDictation(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return status('Dictée vocale non disponible dans ce navigateur.','bad');const r=new SR();r.lang='fr-FR';r.interimResults=false;r.continuous=false;$('mic').textContent='🎙️…';r.onresult=e=>{const txt=e.results?.[0]?.[0]?.transcript||'';$('input').value=($('input').value+' '+txt).trim();updateCounter()};r.onerror=e=>status('Dictée : '+e.error,'bad');r.onend=()=>{$('mic').textContent='🎙️'};r.start()}
function renderKnowledge(){const box=$('knowledge-list'),k=knowledge();box.replaceChildren();if(!k.length){box.innerHTML='<div class="note">Aucune connaissance injectée pour le moment.</div>';return}k.forEach((d,i)=>{const row=document.createElement('div');row.className='knowledge-item';const b=document.createElement('b');b.textContent=d.title+' · '+Math.round(d.text.length/1000)+'k';const x=document.createElement('button');x.className='mini';x.textContent='✕';x.onclick=()=>{const n=knowledge();n.splice(i,1);saveKnowledge(n)};row.append(b,x);box.appendChild(row)})}
function addDoc(title,text){text=String(text||'').trim();if(!text)return;const k=knowledge();k.push({id:crypto.randomUUID(),title:String(title||'Connaissance').slice(0,120),text:text.slice(0,250000),addedAt:Date.now()});saveKnowledge(k)}
function addPastedKnowledge(){const t=$('knowledge-paste').value.trim();if(!t)return;const title=prompt('Nom de cette connaissance :','Méthode d’écriture')||'Méthode d’écriture';addDoc(title,t);$('knowledge-paste').value='';status('Connaissance injectée.','ok')}
async function importKnowledgeFiles(e){const files=Array.from(e.target.files||[]);for(const f of files){try{addDoc(f.name,await f.text())}catch(_){status('Impossible de lire '+f.name,'bad')}}e.target.value='';status(files.length+' fichier(s) de connaissance ajouté(s).','ok')}
function clearKnowledge(){if(!confirm('Retirer toutes les connaissances d’écriture de ce studio ?'))return;saveKnowledge([]);status('Base de connaissances vidée.','ok')}
document.addEventListener('DOMContentLoaded',init);if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=function(){};
})();
